name: 'fmk_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'fmk_dbt_user'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets:        
  - "target"
  - "dbt_modules"

models:
  fmk_dbt_project:
    # Config indicated by + and applies to all files under models/example/
    sources:
      +materialized: view
      heap: 
        +materialized: incremental
        
