
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'fmk_dbt_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'fmk_dbt_user'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  fmk_dbt_project:
    # Config indicated by + and applies to all files under models/example/
    staging:
      heap:
        stg_heap_users:
          materialized: ephemeral
        stg_heap_sessions:
          materialized: ephemeral
        stg_heap_pageviews:
          materialized: ephemeral
        stg_heap_events:
          materialized: ephemeral
    transformed:
      heap:
        heap_users_dim:
          materialized: incremental
        heap_sessions_fct:
          materialized: incremental
        heap_pageviews_fct:
          materialized: incremental
        heap_events_fct:
          materialized: incremental
    fmk_core:
      fmk_users_dim:
        materialized: incremental
      fmk_conversions:
        materialized: incremental
    explores:
      hourly_signup_flow_l7:
        materialized: table
      daily_signup_flow_l30:
        materialized: table
